version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BASE_URL
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
    depends_on:
      - redis

  redis:
    image: "redis:alpine"